steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-m', '30g', '-t', 'gcr.io/dockertest-259701/cpc:custom', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dockertest-259701/cpc:custom']
options:
 machineType: 'N1_HIGHCPU_32'
timeout: 7200s
